import { useState, useEffect } from 'react'
import { useParams, useNavigate, useLocation } from 'react-router-dom'
import { tripAPI } from '../services/api'

const NEARBY_CATS = [
  { id: 'food', label: 'Restaurants', icon: '🍽️' },
  { id: 'hotel', label: 'Hotels', icon: '🏨' },
  { id: 'attraction', label: 'Attractions', icon: '🎯' },
  { id: 'heritage', label: 'Heritage', icon: '🏛️' },
  { id: 'emergency', label: 'ATM / Hospital', icon: '🏥' },
  { id: 'nature', label: 'Nature', icon: '🌿' },
]

export default function TripResult() {
  const { id } = useParams()
  const navigate = useNavigate()
  const location = useLocation()
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)
  const [showMap, setShowMap] = useState(true)
  const [morePlaces, setMorePlaces] = useState([])
  const [moreLoading, setMoreLoading] = useState(false)
  const [selectedCat, setSelectedCat] = useState(null)
  const [moreOffset, setMoreOffset] = useState(0)

  useEffect(() => {
    if (location.state?.rescueData) { setData(location.state.rescueData); setLoading(false); return }
    if (!id || id === 'rescue') { setError('No trip ID available.'); setLoading(false); return }
    tripAPI.getTrip(id).then(r => setData(r.data)).catch(() => setError('Failed to load trip.')).finally(() => setLoading(false))
  }, [id, location.state])

  const handleSave = async () => {
    if (!data?.tripId) return
    setSaving(true)
    try { await tripAPI.save(data.tripId); alert('Saved to history!') }
    catch { alert('Failed to save.') }
    finally { setSaving(false) }
  }

  const handleShowMore = async (cat) => {
    setSelectedCat(cat)
    setMoreLoading(true)
    const offset = cat === selectedCat ? moreOffset + 5 : 0
    setMoreOffset(offset)
    try {
      const res = await tripAPI.morePlaces(id, cat, offset)
      setMorePlaces(res.data || [])
    } catch { setMorePlaces([]) }
    finally { setMoreLoading(false) }
  }

  const mapsDir = () => {
    if (!data) return '#'
    const places = data.suggestedPlaces || []
    const wps = places.map(p => p.latitude && p.longitude ? `${p.latitude},${p.longitude}` : p.name).join('|')
    const wpParam = wps ? `&waypoints=${encodeURIComponent(wps)}` : ''
    return `https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(data.startLocation)}&destination=${encodeURIComponent(data.destination)}${wpParam}&travelmode=driving`
  }

  const placeMapUrl = (p) => p.latitude && p.longitude
    ? `https://www.google.com/maps/search/?api=1&query=${p.latitude},${p.longitude}`
    : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.name)}`

  const dirToPlace = (p) => `https://www.google.com/maps/dir/?api=1&destination=${
    p.latitude && p.longitude ? `${p.latitude},${p.longitude}` : encodeURIComponent(p.name)
  }&travelmode=driving`

  const downloadPDF = () => {
    const places = data?.suggestedPlaces || []
    const content = [
      `VYNTRA TRIP PLAN`,
      `================`,
      `Route: ${data?.startLocation} → ${data?.destination}`,
      `Travel Time: ${data?.estimatedTravelTime || 'N/A'}`,
      `Estimated Cost: ₹${data?.estimatedTotalCost || 0}`,
      `Weather: ${data?.weatherSummary || 'N/A'}`,
      ``,
      `STOPS (${places.length}):`,
      ...places.map((p, i) => [
        `${i+1}. ${p.name} [${p.category}]`,
        `   Address: ${p.address || 'Near route'}`,
        `   Rating: ${p.rating ? p.rating.toFixed(1) : 'N/A'} | Cost: ₹${p.estimatedCost ? Math.round(p.estimatedCost) : 0}`,
        `   Maps: ${placeMapUrl(p)}`,
      ].join('\n')),
      ``,
      `AI SUMMARY:`,
      data?.aiSummary || 'No summary available.',
      ``,
      `Full Directions: ${mapsDir()}`,
      `Generated by Vyntra – vyntra.app`,
    ].join('\n')
    const blob = new Blob([content], { type: 'text/plain' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `vyntra-trip-${data?.startLocation}-to-${data?.destination}.txt`
    a.click()
  }

  if (loading) return (
    <div style={{ display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'center', minHeight:'60vh', gap:'1rem' }}>
      <div className="spinner-teal" style={{ width:40, height:40 }} />
      <p style={{ color:'#64748b', fontWeight:500 }}>Finding real places along your route…</p>
    </div>
  )
  if (error) return <div style={{ padding:'1.5rem', backgroundColor:'#fef2f2', color:'#dc2626', borderRadius:'0.75rem' }}>{error}</div>
  if (!data) return null

  const places = data.suggestedPlaces || []
  const removed = data.removedPlaces || []

  return (
    <div style={{ maxWidth:'1100px', margin:'0 auto', paddingBottom:'5rem' }} className="fade-in">

      {/* ── Header Banner ── */}
      <div style={{ background:'linear-gradient(135deg,#0f766e,#115e59)', borderRadius:'1rem', padding:'2rem', marginBottom:'2rem', position:'relative', overflow:'hidden', boxShadow:'0 8px 32px rgba(15,118,110,0.25)' }}>
        <div style={{ position:'absolute', right:-40, top:-40, width:200, height:200, background:'rgba(255,255,255,0.05)', borderRadius:'50%' }} />
        <div style={{ position:'relative', zIndex:1 }}>
          <div style={{ display:'flex', gap:'0.5rem', alignItems:'center', color:'#99f6e4', fontSize:'0.8rem', fontWeight:600, marginBottom:'0.75rem' }}>
            <span>FROM</span><span style={{ flex:1, height:1, background:'rgba(153,246,228,0.3)' }} /><span>TO</span>
          </div>
          <h1 style={{ color:'#ffffff', fontFamily:'Outfit', fontSize:'clamp(1.4rem,3vw,2rem)', fontWeight:800, marginBottom:'1rem' }}>
            {data.startLocation} <span style={{ opacity:0.5 }}>→</span> {data.destination}
          </h1>
          <div style={{ display:'flex', flexWrap:'wrap', gap:'1rem', fontSize:'0.85rem', color:'#ccfbf1', marginBottom:'1.25rem' }}>
            <span>⏱️ {data.estimatedTravelTime || 'N/A'}</span>
            <span>💰 ₹{data.estimatedTotalCost || 0}</span>
            <span>📍 {places.length} stops</span>
            {data.weatherSummary && <span style={{ marginLeft:'auto', background:'rgba(255,255,255,0.1)', padding:'0.25rem 0.75rem', borderRadius:'9999px' }}>🌤️ {data.weatherSummary}</span>}
          </div>
          <div style={{ display:'flex', flexWrap:'wrap', gap:'0.75rem' }}>
            <a href={mapsDir()} target="_blank" rel="noopener noreferrer"
              style={{ display:'inline-flex', alignItems:'center', gap:'0.5rem', background:'#ffffff', color:'#0f766e', fontWeight:700, fontSize:'0.85rem', padding:'0.6rem 1.25rem', borderRadius:'0.75rem', textDecoration:'none' }}>
              🗺️ Open Full Route in Google Maps
            </a>
            <button onClick={() => setShowMap(m => !m)}
              style={{ background:'rgba(255,255,255,0.15)', color:'#ffffff', border:'1px solid rgba(255,255,255,0.3)', fontWeight:600, fontSize:'0.85rem', padding:'0.6rem 1.25rem', borderRadius:'0.75rem', cursor:'pointer' }}>
              {showMap ? 'Hide Map' : 'Show Map'}
            </button>
            <button onClick={downloadPDF}
              style={{ background:'rgba(255,255,255,0.1)', color:'#ffffff', border:'1px solid rgba(255,255,255,0.2)', fontWeight:600, fontSize:'0.85rem', padding:'0.6rem 1.25rem', borderRadius:'0.75rem', cursor:'pointer' }}>
              📄 Download Plan
            </button>
          </div>
        </div>
      </div>

      {/* ── Map Embed ── */}
      {showMap && (
        <div className="card fade-in" style={{ marginBottom:'2rem', overflow:'hidden' }}>
          <div style={{ padding:'0.75rem 1.25rem', borderBottom:'1px solid #e2e8f0', display:'flex', justifyContent:'space-between', alignItems:'center', background:'#f8fafc' }}>
            <span style={{ fontWeight:700, color:'#0f172a', fontSize:'0.9rem' }}>🗺️ Route Map</span>
            <a href={mapsDir()} target="_blank" rel="noopener noreferrer" style={{ fontSize:'0.75rem', color:'#0f766e', fontWeight:600 }}>Open Full ↗</a>
          </div>
          <div style={{ position:'relative', paddingBottom:'42%', minHeight:300 }}>
            <iframe
              style={{ position:'absolute', inset:0, width:'100%', height:'100%', border:0 }}
              loading="lazy" allowFullScreen referrerPolicy="no-referrer-when-downgrade"
              src={`https://www.google.com/maps/embed/v1/directions?key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8&origin=${encodeURIComponent(data.startLocation)}&destination=${encodeURIComponent(data.destination)}&mode=driving`}
            />
          </div>
        </div>
      )}

      {/* ── Main Grid ── */}
      <div style={{ display:'grid', gridTemplateColumns:'1fr', gap:'2rem' }} className="lg-grid-3">

        {/* ── Stops Timeline ── */}
        <div style={{ gridColumn:'1 / span 2' }}>
          <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'1rem' }}>
            <h2 style={{ fontFamily:'Outfit', fontWeight:700, color:'#0f172a', fontSize:'1.2rem' }}>Optimized Route Stops</h2>
            <span className="badge badge-slate">{places.length} stops</span>
          </div>

          {places.length === 0
            ? <div className="card" style={{ padding:'2rem', textAlign:'center', color:'#64748b' }}>No stops found. Try a different route or style.</div>
            : (
              <div style={{ borderLeft:'2px solid #e2e8f0', marginLeft:'1rem', paddingBottom:'1rem' }}>
                {places.map((place, idx) => (
                  <div key={idx} style={{ position:'relative', paddingLeft:'2rem', marginBottom:'1.5rem' }} className="fade-in">
                    <div style={{ position:'absolute', left:-9, top:4, width:16, height:16, borderRadius:'50%', background:'#ffffff', border:'4px solid #0f766e', boxShadow:'0 1px 4px rgba(0,0,0,0.1)' }} />
                    <div className="card" style={{ padding:'1.25rem' }}>
                      <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:'0.5rem', flexWrap:'wrap', gap:'0.5rem' }}>
                        <div style={{ display:'flex', gap:'0.5rem', flexWrap:'wrap' }}>
                          <span className="badge badge-teal">{place.category || 'general'}</span>
                          {place.openNow === false && <span className="badge badge-amber">May be closed</span>}
                        </div>
                        <div style={{ display:'flex', gap:'0.75rem', fontSize:'0.75rem', fontWeight:700 }}>
                          {place.score > 0 && <span style={{ color:'#059669', background:'#ecfdf5', padding:'0.15rem 0.5rem', borderRadius:'9999px', border:'1px solid #a7f3d0' }}>Score: {Math.round(place.score)}</span>}
                          {place.rating && <span style={{ color:'#b45309' }}>★ {Number(place.rating).toFixed(1)}</span>}
                        </div>
                      </div>
                      <h3 style={{ color:'#0f172a', fontWeight:700, fontSize:'1rem', marginBottom:'0.25rem' }}>{place.name}</h3>
                      <p style={{ color:'#64748b', fontSize:'0.8rem', marginBottom:'0.75rem' }}>{place.address || 'Near your route'}</p>
                      {place.reason && (
                        <div style={{ background:'#f8fafc', border:'1px solid #f1f5f9', borderRadius:'0.5rem', padding:'0.6rem 0.75rem', marginBottom:'0.75rem', fontSize:'0.8rem', color:'#475569' }}>
                          <span style={{ color:'#0f766e', fontWeight:700 }}>↳ </span>{place.reason}
                        </div>
                      )}
                      <div style={{ display:'flex', gap:'1rem', fontSize:'0.75rem', color:'#64748b', fontWeight:600, marginBottom:'0.75rem' }}>
                        {place.distanceFromRoute != null && <span>📍 {place.distanceFromRoute} km off-route</span>}
                        {place.estimatedCost != null && <span>💵 ₹{Math.round(place.estimatedCost)}</span>}
                      </div>
                      <div style={{ display:'flex', flexWrap:'wrap', gap:'0.5rem', paddingTop:'0.75rem', borderTop:'1px solid #f1f5f9' }}>
                        <a href={placeMapUrl(place)} target="_blank" rel="noopener noreferrer"
                          style={{ display:'inline-flex', alignItems:'center', gap:'0.35rem', padding:'0.35rem 0.75rem', borderRadius:'0.5rem', fontSize:'0.75rem', fontWeight:600, background:'#f0fdfa', color:'#0f766e', border:'1px solid #99f6e4', textDecoration:'none' }}>
                          📍 View on Map
                        </a>
                        <a href={dirToPlace(place)} target="_blank" rel="noopener noreferrer"
                          style={{ display:'inline-flex', alignItems:'center', gap:'0.35rem', padding:'0.35rem 0.75rem', borderRadius:'0.5rem', fontSize:'0.75rem', fontWeight:600, background:'#eff6ff', color:'#1d4ed8', border:'1px solid #bfdbfe', textDecoration:'none' }}>
                          🧭 Directions
                        </a>
                        <a href={`https://www.google.com/maps/search/restaurants+near+${place.latitude},${place.longitude}`} target="_blank" rel="noopener noreferrer"
                          style={{ display:'inline-flex', alignItems:'center', gap:'0.35rem', padding:'0.35rem 0.75rem', borderRadius:'0.5rem', fontSize:'0.75rem', fontWeight:600, background:'#fffbeb', color:'#b45309', border:'1px solid #fde68a', textDecoration:'none' }}>
                          🍽️ Nearby Food
                        </a>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}

          {/* ── Show More ── */}
          <div className="card" style={{ padding:'1.5rem', marginTop:'1.5rem', borderTop:'4px solid #10b981' }}>
            <h3 style={{ fontFamily:'Outfit', fontWeight:700, color:'#0f172a', marginBottom:'0.5rem', fontSize:'1rem' }}>
              📍 Find More Places Along Route
            </h3>
            <p style={{ color:'#64748b', fontSize:'0.8rem', marginBottom:'1rem' }}>Discover additional spots in any category:</p>
            <div style={{ display:'flex', flexWrap:'wrap', gap:'0.5rem', marginBottom:'1rem' }}>
              {NEARBY_CATS.map(cat => (
                <button key={cat.id} onClick={() => handleShowMore(cat.id)}
                  style={{
                    padding:'0.5rem 1rem', borderRadius:'0.75rem', fontSize:'0.8rem', fontWeight:600, cursor:'pointer', transition:'all 0.2s',
                    background: selectedCat === cat.id ? '#0f766e' : '#f8fafc',
                    color: selectedCat === cat.id ? '#ffffff' : '#475569',
                    border: selectedCat === cat.id ? 'none' : '1px solid #e2e8f0',
                  }}>
                  {cat.icon} {cat.label}
                </button>
              ))}
            </div>
            {moreLoading && <p style={{ color:'#94a3b8', fontSize:'0.85rem' }}>Searching real places…</p>}
            {!moreLoading && morePlaces.length > 0 && (
              <div style={{ display:'grid', gap:'0.75rem' }}>
                {morePlaces.map((p, i) => (
                  <div key={i} style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'0.75rem 1rem', background:'#f8fafc', borderRadius:'0.75rem', border:'1px solid #e2e8f0' }}>
                    <div>
                      <p style={{ fontWeight:600, color:'#0f172a', fontSize:'0.875rem' }}>{p.name}</p>
                      <p style={{ color:'#64748b', fontSize:'0.75rem' }}>{p.address || 'Near route'} • {p.rating ? `★${Number(p.rating).toFixed(1)}` : ''} {p.estimatedCost ? `• ₹${Math.round(p.estimatedCost)}` : ''}</p>
                    </div>
                    <a href={placeMapUrl(p)} target="_blank" rel="noopener noreferrer"
                      style={{ padding:'0.4rem 0.75rem', background:'#f0fdfa', color:'#0f766e', borderRadius:'0.5rem', fontSize:'0.75rem', fontWeight:600, textDecoration:'none', border:'1px solid #99f6e4', whiteSpace:'nowrap' }}>
                      View →
                    </a>
                  </div>
                ))}
                <button onClick={() => handleShowMore(selectedCat)}
                  style={{ padding:'0.6rem', border:'1px dashed #cbd5e1', borderRadius:'0.75rem', color:'#64748b', fontSize:'0.8rem', cursor:'pointer', background:'none' }}>
                  Load More {selectedCat} →
                </button>
              </div>
            )}
          </div>
        </div>

        {/* ── Right Column ── */}
        <div style={{ display:'flex', flexDirection:'column', gap:'1.5rem' }}>
          {/* Directions Panel */}
          <div className="card" style={{ padding:'1.5rem', borderTop:'4px solid #3b82f6' }}>
            <h3 style={{ fontFamily:'Outfit', fontWeight:700, color:'#0f172a', marginBottom:'1rem', fontSize:'1rem' }}>🧭 Trip Directions</h3>
            <div style={{ display:'flex', flexDirection:'column', gap:'0.6rem', marginBottom:'1rem' }}>
              <div style={{ display:'flex', gap:'0.75rem', alignItems:'center', padding:'0.75rem', background:'#ecfdf5', borderRadius:'0.75rem' }}>
                <div style={{ width:32, height:32, borderRadius:'50%', background:'#10b981', display:'flex', alignItems:'center', justifyContent:'center', color:'#fff', fontWeight:700, fontSize:'0.75rem', flexShrink:0 }}>A</div>
                <div>
                  <p style={{ fontSize:'0.7rem', color:'#059669', fontWeight:700, textTransform:'uppercase', letterSpacing:'0.05em' }}>Start</p>
                  <p style={{ fontSize:'0.85rem', fontWeight:600, color:'#0f172a' }}>{data.startLocation}</p>
                </div>
              </div>
              {places.map((p, i) => (
                <div key={i} style={{ display:'flex', gap:'0.75rem', alignItems:'center', padding:'0.6rem 0.75rem', background:'#f8fafc', borderRadius:'0.75rem', border:'1px solid #f1f5f9' }}>
                  <div style={{ width:28, height:28, borderRadius:'50%', background:'#0f766e', display:'flex', alignItems:'center', justifyContent:'center', color:'#fff', fontWeight:700, fontSize:'0.7rem', flexShrink:0 }}>{i+1}</div>
                  <div style={{ flex:1, minWidth:0 }}>
                    <p style={{ fontSize:'0.82rem', fontWeight:600, color:'#0f172a', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }}>{p.name}</p>
                    <p style={{ fontSize:'0.7rem', color:'#94a3b8' }}>{p.category}</p>
                  </div>
                  <a href={dirToPlace(p)} target="_blank" rel="noopener noreferrer" style={{ color:'#0f766e', textDecoration:'none', fontSize:'1rem' }}>➜</a>
                </div>
              ))}
              <div style={{ display:'flex', gap:'0.75rem', alignItems:'center', padding:'0.75rem', background:'#fef2f2', borderRadius:'0.75rem' }}>
                <div style={{ width:32, height:32, borderRadius:'50%', background:'#ef4444', display:'flex', alignItems:'center', justifyContent:'center', color:'#fff', fontWeight:700, fontSize:'0.75rem', flexShrink:0 }}>B</div>
                <div>
                  <p style={{ fontSize:'0.7rem', color:'#dc2626', fontWeight:700, textTransform:'uppercase', letterSpacing:'0.05em' }}>Destination</p>
                  <p style={{ fontSize:'0.85rem', fontWeight:600, color:'#0f172a' }}>{data.destination}</p>
                </div>
              </div>
            </div>
            <a href={mapsDir()} target="_blank" rel="noopener noreferrer" className="btn-primary" style={{ width:'100%', justifyContent:'center', textDecoration:'none', display:'flex' }}>
              Navigate Full Route 🗺️
            </a>
          </div>

          {/* AI Summary */}
          <div className="card" style={{ padding:'1.5rem', borderTop:'4px solid #8b5cf6' }}>
            <h3 style={{ fontFamily:'Outfit', fontWeight:700, color:'#0f172a', marginBottom:'1rem', fontSize:'1rem' }}>✨ AI Trip Summary</h3>
            {data.aiSummary
              ? <p style={{ color:'#475569', fontSize:'0.875rem', lineHeight:1.7, whiteSpace:'pre-line' }}>{data.aiSummary}</p>
              : <p style={{ color:'#94a3b8', fontSize:'0.85rem', fontStyle:'italic' }}>No summary available.</p>}
          </div>

          {/* Actions */}
          <div style={{ display:'flex', flexDirection:'column', gap:'0.75rem' }}>
            {data.tripId && (
              <button onClick={handleSave} disabled={saving} className="btn-primary" style={{ width:'100%' }}>
                {saving ? 'Saving…' : '💾 Save to History'}
              </button>
            )}
            <button onClick={downloadPDF} className="btn-secondary" style={{ width:'100%', color:'#0f172a' }}>
              📄 Download Trip Plan
            </button>
            <button onClick={() => navigate('/rescue')} className="btn-secondary" style={{ width:'100%', color:'#ea580c', borderColor:'#fed7aa' }}>
              🚨 Rescue Mode
            </button>
            <button onClick={() => navigate('/plan')} className="btn-secondary" style={{ width:'100%' }}>
              🗺️ Plan Another Trip
            </button>
          </div>

          {/* Filtered Places */}
          {removed.length > 0 && (
            <div className="card" style={{ padding:'1.25rem', background:'#f8fafc', borderStyle:'dashed' }}>
              <h3 style={{ fontSize:'0.75rem', fontWeight:700, color:'#64748b', textTransform:'uppercase', letterSpacing:'0.05em', marginBottom:'0.75rem' }}>Filtered by Constraints</h3>
              {removed.map((r, i) => (
                <div key={i} style={{ paddingBottom:'0.6rem', borderBottom: i < removed.length-1 ? '1px solid #e2e8f0' : 'none', marginBottom:'0.6rem' }}>
                  <p style={{ fontWeight:600, color:'#94a3b8', textDecoration:'line-through', fontSize:'0.8rem' }}>{r.name}</p>
                  <p style={{ fontSize:'0.7rem', color:'#ef4444', marginTop:'0.15rem' }}>{r.reasonRemoved}</p>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
